// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2jMwKpr9PMRcKVKsEhZ91wXYM221yeto',
    appId: '1:762951769568:web:bc875f8b99310dad4b9f85',
    messagingSenderId: '762951769568',
    projectId: 'chat-app-97248',
    authDomain: 'chat-app-97248.firebaseapp.com',
    storageBucket: 'chat-app-97248.firebasestorage.app',
    measurementId: 'G-JZW7YVXBN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_GkbGg5fHciQ-GYMyl-ZtEJ6rfBGX7N8',
    appId: '1:762951769568:android:8e99bcebb398f5734b9f85',
    messagingSenderId: '762951769568',
    projectId: 'chat-app-97248',
    storageBucket: 'chat-app-97248.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4KKHEVMRE4Z1-xx4QcrlbLdLXs-RASYo',
    appId: '1:762951769568:ios:0098bd7232af110f4b9f85',
    messagingSenderId: '762951769568',
    projectId: 'chat-app-97248',
    storageBucket: 'chat-app-97248.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
